Adding paragraph and sentence chunking strategy.
dgarnitz/vectorflow pull request #30
Opened 2023-08-24 07:26 UTC by EteimZ

## what

This PR is adding the ability to performing text chunking by paragraph and sentence as per the request of issue: #12 

## why

Currently vectorflow only allows to chunk by the exact values specified by the user in the request. This PR seeks to make the chunking procedure less manual.

## verification

Unit tests have been written in the test_worker.py [file](https://github.com/EteimZ/vectorflow/blob/feature_chunking_strategy/src/worker/tests/test_worker.py) between line [62](https://github.com/EteimZ/vectorflow/blob/feature_chunking_strategy/src/worker/tests/test_worker.py#L62) and [89](https://github.com/EteimZ/vectorflow/blob/feature_chunking_strategy/src/worker/tests/test_worker.py#L89)

## Usage

2023-08-25 02:00 UTC, dgarnitz requested changes
This is a great work! A few small changes and this will be ready to go

2023-08-28 10:22 UTC, EteimZ commented on src/worker/worker.py
> +    # data = "".join(data_chunks)
I will change this

2023-08-28 10:28 UTC, EteimZ commented on src/worker/worker.py
> +    sentence_endings = r'(?<=[.!?…]) +'
Sure thing

2023-08-28 10:31 UTC, EteimZ commented on src/worker/tests/test_worker.py
> +    def test_chunk_paragraph_bound(self):
This is to test the overlap in the split.

2023-08-28 10:31 UTC, EteimZ commented on src/worker/worker.py
> +def chunk_data_by_paragraph(data, chunk_size, over_lap, bound=0.75):
Noted

2023-08-30 13:43 UTC, dgarnitz commented
Looks great! Is it working when you run it in Docker? If so, please post a screenshot then I'll approve it and merge it

2023-08-30 17:54 UTC, dgarnitz approved these changes

2023-08-30 17:54 UTC, merged